### PR TITLE
Osx GDB build fix

### PR DESCRIPTION
**Pull request by prb28**
Builds on osx mojave 10.14.5.
I've used the gcc from brew, it resolved the compile errors.

I've tested the gdb build to debug with bgdbserver on vscode and it worked!

### CODE REVIEW

**Comment by bebbo** [comment]
A cheer goes through the crowd of the OSX community...

**Comment by prb28** [comment]
I did no try on travis and it doesn't seems to pass.
Do you want some help ? maybe I've missed something in the build config (I've made 'some' tries before it worked;-) so there may be something different in my host)

**Comment by prb28** [comment]
This may work, I'm waiting for the result in https://travis-ci.org/prb28/amiga-gcc (it takes more than 30min)
```yaml
branches:
  only:
  - master
addons:
  homebrew:
    taps: discoteq/discoteq
    packages:
      - bash
      - make
      - lhasa
      - flex
      - gettext
      - texinfo
      - flock
      # needed but already installed : gcc autoconf wget gmp mpfr libmpc
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      sudo: required
      language: c
      before_install:
        - sudo mkdir /opt/amiga && sudo chown $(whoami) /opt/amiga
script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ];
    then 
      export CC=gcc-8;
      export CXX=g++-8;
      travis_wait 60 gmake all -j3;
    else
      make all -j3;
    fi
after_failure:
  - cat log/*.log
```

**Comment by bebbo** [comment]
you travis-ci build succeeded. I'm grabbing it :-)

**Pull request merged**
